spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fermetroistilleuls
    username: ferme_user
    password: Fermedufay2026@
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
